name: CI

on:
  push:
  pull_request:

jobs:
  fair:                              # ── job 1
    name: FAIR Software Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Measure compliance with fair‑software.eu
        uses: fair-software/howfairis-github-action@0.2.1
        with:
          MY_REPO_URL: https://github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




  train-sdm:
    needs: fair
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Use setup-python to get Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 2) Install your dependencies with pip
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygbif geopandas scikit-learn joblib pandas shapely pyproj

      # 3) Run your data‐fetch and model‐train scripts
      - name: Train pollinator SDM
        run: |
          python scripts/fetch_gbif.py
          python scripts/join_env_pollinators.py
          python scripts/train_sdm.py

      # 4) Upload the trained model artifact
      - uses: actions/upload-artifact@v4
        with:
          name: pollinator_sdm
          path: models/pollinator_sdm.joblib
