name: CI

on:
  push:
  pull_request:

jobs:
  fair:                              # ── job 1
    name: FAIR Software Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Measure compliance with fair‑software.eu
        uses: fair-software/howfairis-github-action@0.2.1
        with:
          MY_REPO_URL: https://github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




  train-sdm:
    needs: fair
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install miniconda & create env from your environment.yml
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: biodt-grassland

      # 2) run your scripts inside that env
      - name: Train pollinator SDM
        run: |
          python scripts/fetch_gbif.py
          python scripts/join_env_pollinators.py
          python scripts/train_sdm.py

      # 3) upload model
      - uses: actions/upload-artifact@v4
        with:
          name: pollinator_sdm
          path: models/pollinator_sdm.joblib

